/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basketballcounter;

import javax.swing.JOptionPane;

/**
 *
 * @author Dejan
 */
public class BasketballCounter extends javax.swing.JFrame {

    /**
     * Creates new form BasketballCounter
     */
    public BasketballCounter() {
        homeTeam = JOptionPane.showInputDialog("Type home team name here: ");
        awayTeam = JOptionPane.showInputDialog("Type away team name here: ");
        
        if(homeTeam == null || awayTeam == null || homeTeam.isEmpty() || awayTeam.isEmpty()) {
            JOptionPane.showMessageDialog(null, "You didn't fill team name!", "Empty Team Name", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        
        initComponents();
        setTitle("Basketball Score Counter");
        
        homeLabel.setText(homeTeam);
        awayLabel.setText(awayTeam);
        
        finishLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeLabel = new javax.swing.JLabel();
        awayLabel = new javax.swing.JLabel();
        homeScore = new javax.swing.JTextField();
        awayScore = new javax.swing.JTextField();
        home1Pt = new javax.swing.JButton();
        home2Pt = new javax.swing.JButton();
        home3Pt = new javax.swing.JButton();
        away3Pt = new javax.swing.JButton();
        away2Pt = new javax.swing.JButton();
        away1Pt = new javax.swing.JButton();
        finalizeButton = new javax.swing.JButton();
        finishLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 300));

        homeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 0, 0));
        homeLabel.setText("Home");

        awayLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        awayLabel.setForeground(new java.awt.Color(0, 51, 255));
        awayLabel.setText("Away");

        homeScore.setEditable(false);
        homeScore.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        homeScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        homeScore.setText("0");
        homeScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeScoreActionPerformed(evt);
            }
        });

        awayScore.setEditable(false);
        awayScore.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        awayScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        awayScore.setText("0");
        awayScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awayScoreActionPerformed(evt);
            }
        });

        home1Pt.setText("1 Point");
        home1Pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1PtActionPerformed(evt);
            }
        });

        home2Pt.setText("2 Points");
        home2Pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2PtActionPerformed(evt);
            }
        });

        home3Pt.setText("3 Points");
        home3Pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3PtActionPerformed(evt);
            }
        });

        away3Pt.setText("3 Points");
        away3Pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away3PtActionPerformed(evt);
            }
        });

        away2Pt.setText("2 Points");
        away2Pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away2PtActionPerformed(evt);
            }
        });

        away1Pt.setText("1 Point");
        away1Pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away1PtActionPerformed(evt);
            }
        });

        finalizeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finalizeButton.setText("Finalize");
        finalizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeButtonActionPerformed(evt);
            }
        });

        finishLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        finishLabel.setText("Finished!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeScore)
                            .addComponent(home1Pt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home2Pt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home3Pt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(finishLabel)
                            .addComponent(finalizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awayScore, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(away2Pt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(away3Pt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(away1Pt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(625, 625, 625)
                        .addComponent(awayLabel)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(finishLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLabel)
                    .addComponent(awayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(awayScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(home1Pt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(home2Pt)
                        .addGap(26, 26, 26)
                        .addComponent(home3Pt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(away1Pt)
                        .addGap(26, 26, 26)
                        .addComponent(away2Pt)
                        .addGap(26, 26, 26)
                        .addComponent(away3Pt)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeScoreActionPerformed

    private void awayScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awayScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awayScoreActionPerformed

    private void home1PtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1PtActionPerformed
        homeScore.setText(Integer.parseInt(homeScore.getText()) + 1 + "");
    }//GEN-LAST:event_home1PtActionPerformed

    private void home2PtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2PtActionPerformed
        homeScore.setText(Integer.parseInt(homeScore.getText()) + 2 + "");
    }//GEN-LAST:event_home2PtActionPerformed

    private void home3PtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3PtActionPerformed
        homeScore.setText(Integer.parseInt(homeScore.getText()) + 3 + "");
    }//GEN-LAST:event_home3PtActionPerformed

    private void away1PtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away1PtActionPerformed
        awayScore.setText(Integer.parseInt(awayScore.getText()) + 1 + "");
    }//GEN-LAST:event_away1PtActionPerformed

    private void away2PtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away2PtActionPerformed
        awayScore.setText(Integer.parseInt(awayScore.getText()) + 2 + "");
    }//GEN-LAST:event_away2PtActionPerformed

    private void away3PtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away3PtActionPerformed
        awayScore.setText(Integer.parseInt(awayScore.getText()) + 3 + "");
    }//GEN-LAST:event_away3PtActionPerformed

    private void finalizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeButtonActionPerformed
        home1Pt.setVisible(false);
        home2Pt.setVisible(false);
        home3Pt.setVisible(false);
        
        away1Pt.setVisible(false);
        away2Pt.setVisible(false);
        away3Pt.setVisible(false);
        
        finishLabel.setVisible(true);
        finalizeButton.setEnabled(false);
    }//GEN-LAST:event_finalizeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasketballCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasketballCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasketballCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasketballCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasketballCounter().setVisible(true);
            }
        });
    }

    //private variables - addition
    private String homeTeam = "", awayTeam = "";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton away1Pt;
    private javax.swing.JButton away2Pt;
    private javax.swing.JButton away3Pt;
    private javax.swing.JLabel awayLabel;
    private javax.swing.JTextField awayScore;
    private javax.swing.JButton finalizeButton;
    private javax.swing.JLabel finishLabel;
    private javax.swing.JButton home1Pt;
    private javax.swing.JButton home2Pt;
    private javax.swing.JButton home3Pt;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JTextField homeScore;
    // End of variables declaration//GEN-END:variables
}
